### ISSUE TITLE
2FA no longer working

### ISSUE THREAD

**Issue by DAPS-Spock** [DAPSCoin/DAPSCoin#114]
When enabling 2FA in the wallet, the resulting code is incorrect.

Steps:
1. Go to the settings screen and enable 2FA.
2. Scan the QR code or enter the recovery code manually
3. Using the Phone app, enter the given code.
4. The entered code will be wrong.

**Comment by lopeed** [comment]
![2FA](https://user-images.githubusercontent.com/35898975/76859734-28dae180-685a-11ea-973f-240556a8e84b.png)

with version 1.0.6.2 and using Google Authenticator

**Comment by lopeed** [comment]
![2FA v1 0 5 8](https://user-images.githubusercontent.com/35898975/76861261-98ea6700-685c-11ea-8ee7-908beab0eb50.png)

and with v1.0.5.8

**Comment by DAPS-Spock** [comment]
I'll upload a screenshot tomorrow about the issue.

**Comment by lyricidal** [comment]
Does this one still remain an issue?

**Comment by DAPS-Spock** [comment]
I haven't seen it pop up again.
Will need to re-test.
