### ISSUE TITLE
Wrong IP Address information on Masternode tab

### ISSUE THREAD

**Issue by lucablighthl** [DAPSCoin/DAPSCoin#135]
**Describe the bug**
When you have several Masternodes hosted in different servers (different IPs), the wallets shows some Masternodes with the right IP and others with wrong IP).

**To Reproduce**
1. Set up more than one Masternode.
2. Host them on different servers (at least two different servers for them).
3. Put all information on the file dapscoin.conf.
4. Open the wallet and check the IP Address information on the Masternode tab.

**Screenshots**
The information on the masternode.conf file is right, but it showed wrong on the wallet:

![Capture](https://user-images.githubusercontent.com/59424539/78316126-42a44600-7535-11ea-877c-1be7a6e23524.jpg)

**Desktop:**
It was tested only on Windows 10.

**Comment by lopeed** [comment]
test version??? what version???

**Comment by lyricidal** [comment]
Has this come up again on any recent versions?

**Comment by lucablighthl** [comment]
Guys, I think this issue can be closed because this bug can be solved just deleting the file mncache.dat
