### ISSUE TITLE
Add mnemonic restore to daemons

### ISSUE THREAD

**Issue by DAPS-Spock** [DAPSCoin/DAPSCoin#139]
Daemons require the ability to restore from mnemonic phrase without the use of the ui.

**Comment by DAPS-Spock** [comment]
Was this ever completed?

**Comment by lyricidal** [comment]
Yes.

Currently the way to do it is:
- Remove or backup any current wallet.dat
- Open dapscoin.conf
- add line
`mnemonic=WORDS x 24` filling in your
- Launch dapscoind
