### ISSUE TITLE
Error on shutdown after using the bootstrap and chainstate to rebuild

### ISSUE THREAD

**Issue by gwestwood** [DAPSCoin/DAPSCoin#15]
The following error occurred after using the bootstrap and chainstate to rebuild (this might not be related to the error):

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

**Comment by akshaynexus** [comment]
Got a debug log?

**Comment by gwestwood** [comment]
> Got a debug log?

Unfortunately I seem to have deleted it sometime between then and now.  That seemed the only relevant line out of the usual though.

**Comment by DAPS-Spock** [comment]
Closing this as it has been fixed completely with 1.0.6.5
