### ISSUE TITLE
Add checkpoints at runtime.

### ISSUE THREAD

**Issue by Swissmade1** [DAPSCoin/DAPSCoin#182]
New checkpoints always need a wallet or daemon update so there can be something done about it.
There has to be a file like checkpoint.dat
In this file are the new checkpoints for the moment. Old checkpoints already in the daemon don't have to be add there. Less time to read.
If the wallet start it gets the new checkpoints from this file and place it in the checkpoint array in the wallet or daemon.
In the wallet, daemon has to be added a new command like getcheckpoints. 
If this command is executed the checkpoints are read from the API. If there new checkpoints then they will be add to checkpoint.dat and the checkpoint array will be reinit without restart the wallet or daemon.
This way we can handle trouble very fast without new versions every time.

Any comment in this please.

**Comment by Swissmade1** [comment]
Wrong place I think this is not a issue but has a branch

**Comment by DAPS-Spock** [comment]
There are a few reasons why we cannot do that:
1. We'd be controlling the chain on the fly
2. It would be seen as centralisation
3. That how consensus rules are working pretty much anyway.
