### ISSUE TITLE
poa-minerd FTL

### ISSUE THREAD

**Issue by Pagliacci-Von-Doom** [DAPSCoin/DAPSCoin#4]
when extracting poa miner from wallet folder, poa miner didn't unpack. downloaded folder again with virus scanner deactivated. launched poa-miner and got error saying application was incompatible (running windows 10 with most recent update)

**Comment by DAPS-Spock** [comment]
So you downloaded the .zip file, extracted it and then attempted to run the PoA miner and then received the error?

**Comment by lyricidal** [comment]
Closed for now. @Pagliacci-Von-Doom if still having this issue please let us know.
Please note that the PoA Miner might be incrrectly flagged by some AV software and this might be what happened here.

**Comment by Pagliacci-Von-Doom** [comment]
It was just the once. After the initial run attempt, I'd briefly get an
icon in the tray on the bottom of the desktop that would eventually
disappear and nothing would show up in the manager (ctrl+alt+del) as a
running process/application
