### ISSUE TITLE
Exception: St9bad_alloc - bad_alloc

### ISSUE THREAD

**Issue by gwestwood** [DAPSCoin/DAPSCoin#7]
From 'getinfo' on the Linux version of dapscoind

"errors": "EXCEPTION: St9bad_alloc       \nstd::bad_alloc       \ndapscoin in ProcessMessages()       \n"

I'll try to get more info on this.

**Comment by gwestwood** [comment]
Possibly useful:
https://github.com/bitcoin/bitcoin/issues/9857
https://github.com/MintcoinCommunity/Mintcoin-Desktop-Wallet/issues/67

**Comment by DAPS-Spock** [comment]
Closing this as it has included with upstream fixes

**Comment by rebroad** [comment]
@DAPS-Spock which upstream fixes were these please?
