### ISSUE TITLE
Compress Linux tar file for release

### ISSUE THREAD

**Issue by gwestwood** [DAPSCoin/DAPSCoin#9]
I suggest that you compress the tar archive you create for Linux (e.g. master_linux-v1.0.2.tar) using gzip or bzip2 to make downloads smaller.

**Comment by nashsclay** [comment]
I personally do strip command then put in zip or tar.gz after I compile everything. @gwestwood is correct. Don't want to do this to windows builds or mac builds as it can corrupt the files in my experience.

**Comment by gwestwood** [comment]
> I personally do strip command then put in zip or tar.gz after I compile everything.
<snip>

`dapscoin-cli: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=6fbd636de4dcd6834496e22a0ff91193570e3834, stripped`

Looks like they are already stripped.

**Comment by akshaynexus** [comment]
Id suggest just using gitian to compile,simple to setup and use
